name: hep
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - scipy
  - matplotlib
  - tabulate
  - jupyterlab
  - scikit-learn
  - pandas
  - uproot
  - vector
  - mplhep
  - ca-certificates
  - openssl
  - pre-commit
  - certifi
  - seaborn
